public class ExceptionExample {
    public static void main(String[] args) {
        try {
            int[] arr = new int[5];
            arr[5] = 10/0; // This will throw an ArithmeticException
        } catch (ArithmeticException e) {
            System.out.println("An ArithmeticException occurred: " + e.getMessage());
        } catch (ArrayIndexOutOfBoundsException e) {
            System.out.println("An ArrayIndexOutOfBoundsException occurred: " + e.getMessage());
        } catch (Exception e) {
            System.out.println("An exception occurred: " + e.getMessage());
        }
    }
}

O/P:-

An ArrayIndexOutOfBoundsException occurred: 5
